{{- if .Values.istio.enable }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.fullName }}
  labels:
    {{- include "validation-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.ports.http }}
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: {{ .Values.fullName }}
{{- end }}