{{- $fullVersionName := include "validation-service.fullversionname" . }}
{{- $packageVersion := include "validation-service.packageVersionName" . }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $fullVersionName }}
  labels:
    {{- include "validation-service.labels" . | nindent 4 }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "validation-service.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "validation-service.deploymentLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "validation-service.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
        # Add writable volumes
        - name: tmp-volume
          emptyDir: { }
        {{- if .Values.debug.enable }}
        - name: jfr-volume
          emptyDir: { }
        {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.required.image.repository }}/{{ .Values.required.image.name }}:{{ .Values.required.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          {{- /* If entrypoint and parameters are both defined, configure them */ -}}
          {{- if .Values.application.entrypoint }}
          {{- if .Values.application.parameters }}
          {{- with .Values.application.entrypoint }}
          command:
            - /usr/local/bin/entrypoint.sh
          {{- end }}
          {{- with .Values.application.parameters }}
          args:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- end }}
          {{- end }}
          # Mount Volumes in container
          volumeMounts:
            - name: tmp-volume
              mountPath: /tmp
          {{- if .Values.debug.enable }}
            - name: jfr-volume
              mountPath: /jfrdump
          {{- end }}
          # Set the Environment Variables for the container
          env:
            {{- include "validation-service.env" . | nindent 12 }}
          # Ports to be exposed from the container
          ports:
            - name: val-port
              containerPort: 8080
              protocol: TCP
            {{- if .Values.debug.enable }}
            - name: val-debug
              containerPort: 9000
              protocol: TCP
            {{- end }}
          # Performs checks to verify that the application is successfully started
          # The Application is marked as failed after periodSeconds*failureThreshold seconds
          startupProbe:
            httpGet:
              path: /actuator/health
              port: val-port
            failureThreshold: 10
            periodSeconds: 30
          # Use SpringBoot Actuator Liveness Chech
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: val-port
            timeoutSeconds: 5
            failureThreshold: 5
            periodSeconds: 30
          # Use SpringBoot Actuator Readiness Chech
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: val-port
            timeoutSeconds: 5
            failureThreshold: 5
            periodSeconds: 10
          # Define Limits and Requested Resources (CPU/RAM)
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if eq (lower (toString (default false .Values.useTopologySpreadConstraints))) "true" }}
      # Configure a topology spread constraint
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app.kubernetes.io/instance: {{ .Release.Name }}
          matchLabelKeys:
            - pod-template-hash
      {{- else }}
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - {{ include "validation-service.name" . }}
                  - key: version
                    operator: In
                    values:
                      - {{ .Chart.AppVersion | quote }}
                  - key: packageName
                    operator: In
                    values:
                      - {{ .Values.required.packages.name | quote }}
                  - key: packageVersion
                    operator: In
                    values:
                      - {{ $packageVersion }}
              topologyKey: "kubernetes.io/hostname"
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
