{{- if not .Values.istio.useDelegationService -}}
{{- if and (.Values.istio.enable) (hasKey .Values.istio "virtualService") (hasKey .Values.istio.virtualService "gateways") (gt (len .Values.istio.virtualService.gateways) 0) }}
{{- $name := .Values.fullName }}
{{- $url := printf "%s.%s.svc.cluster.local" $name .Release.Namespace }}
{{- $port := .Values.service.ports.http }}

apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: "{{ $name }}-virtual-service-external"
spec:
  {{- if .Values.istio.virtualService.hosts }}
  hosts:
    {{- toYaml .Values.istio.virtualService.hosts | nindent 4 }}
  {{- end}}
  {{- if .Values.istio.virtualService.gateways }}
  gateways:
    {{- toYaml .Values.istio.virtualService.gateways | nindent 4 }}
  {{- end}}
  http:
    - match:
        {{- include "istio.service.external.match" . | nindent 6 }}
      {{- include "istio.service.external.rewrite.url" . | nindent 6 }}
      {{- include "istio.service.external.retry" . | nindent 6 }}
      {{- include "istio.service.external.timeout" . | nindent 6 }}
      route:
        {{- range $k, $v := .Values.istio.subsets }}
        - destination:
            host: {{ $url }}
            subset: {{ include "istio.generate-subset-name" $v }}
            port:
              number: {{ $port }}
          weight: {{ $v.weight }}
          {{- if $v.mirror }}
          mirror:
            host: {{ $url }}
            subset: {{ include "istio.generate-subset-name" $v.mirror }}
            mirrorPercentage:
              value: {{ $v.mirror.mirrorPercentage }}
          {{- end }}
        {{- end }}
{{- end }}
{{- end }}